version: 2.1
orbs:
  docker: circleci/docker@1.3.0
jobs:
  build:
    docker:
      - image: xyzsam/smaug:latest
    environment:
      ALADDIN_HOME: /root/project
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd common
            make all -j2
            cd ../unit-test
            make all -j4
      - run:
          name: Run unit tests
          command: |
            cd unit-test
            export TEST_REPORT_DIR=/root/project/junit_report_dir
            make junit_test
